### ISSUE TITLE
Add the ability to search for the packages, instead of simply showing the installed ones

### ISSUE THREAD

**Issue by mikebdp2** [Cogitri/gnome-software-plugin-apk#28]
Currently, gnome-software only shows the installed packages, but can't search / suggest any packages that haven't been already installed. So, it's useless for me at the moment, but I hope you could change this by adding the ability to search for the packages or browse them by the categories.

Doing this requires the integration with "apk" tool, therefore I'm filing this issue here instead of the official gnome-software repository

**Comment by Cogitri** [comment]
This should already work via appstream-data. What release and OS are you on?

CC @pabloyoyoista this still works on pmOS, right?

**Comment by pabloyoyoista** [comment]
@mikebdp2, thanks a lot for filling the issue here. Please verify that my description here fits the behavior you are experimenting.

@Cogitri, in the general case it does not work. I believe the reason is that a fair amount of non-installed apps that go through the plugin refine function are mostly ignored. For example, if trying to install GNOME chess, just looking for chess will not work, even though the appstream plugin identifies it. However, it is possible to make software display the said app by looking for "gnome-chess" (in the pinephone this is terribly slow, so one might need to wait a bit until it shows up). I have a very WIP branch which might fix this together with the initial carousel now showing. Could push it if somebody is interested in looking at it. But it's really, really WIP.

**Comment by pabloyoyoista** [comment]
Actually, with the regenerated appstream data, some patches to GNOME Software and more powerful hardware than the pinephone, I was able to have this fixed. So looks like my hypothesis is wrong. It might be worth to keep this opened because with the current status searching for apps is not pleasant. Will re-review it once we have the appstream improvements are in place.

**Comment by mikebdp2** [comment]
@pabloyoyoista Thank you very much, when the newer version of GNOME Software will get into Alpine/PostmarketOS repos I will re-test it

**Comment by mikebdp2** [comment]
@pabloyoyoista @Cogitri now I'm running gnome-software 41.3 and gnome-software-plugin-apk 0.9.1 on Alpine/PostmarketOS fully-updated edge, but still have a problem: still can only see the already-installed stuff there

**Comment by pabloyoyoista** [comment]
Needs https://gitlab.com/postmarketOS/pmaports/-/merge_requests/2875 to be fully functional in pmOS. Your testing and input in that MR would also be welcomed. If you are using the package directly from alpine, or if testing is unsuccessful, we really need logs. Otherwise we can't help :(

**Comment by pabloyoyoista** [comment]
Mmmm, I just came to my mind. Maybe it has to be with how we handle the `GCancellable` calls. Unless the cancellation happens during a DBus call, we are basically ignoring those. Which might a reason for GS to get confused and not display anything. I haven't done any further investigation to verify if this is the case, though...

**Comment by pabloyoyoista** [comment]
I was able to reproduce this, and it looks like the main reason in the PinePhone are timeout, since all actions are still synchronous. I am hoping that fixing #44 will also fix this.
